version: '3' # composeファイルのバーション指定
services:
  app: # service名
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    volumes:
      - ./app:/go/src/app  # マウントディレクトリ指定
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - "db"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sendQ_database
      MYSQL_USER: sendQ_user
      MYSQL_PASSWORD: sendQ_password
      TZ: 'Azia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
volumes:
  db-data:
    driver: local